name: 'Install mp-units'
description: 'Install mp-units for CI'

runs:
  using: "composite"
  steps:
    - name: Install gsl-lite
      shell: bash
      run: |
        git clone https://github.com/gsl-lite/gsl-lite && cd gsl-lite
        git checkout v0.40.0
        mkdir build && cd build
        cmake .. && make -j8
        sudo make install

    - name: Install Catch2
      shell: bash
      run: |
        git clone https://github.com/catchorg/Catch2 && cd Catch2
        mkdir build && cd build
        cmake .. && make -j8
        sudo make install

    - name: Install fmt
      shell: bash
      run: |
        git clone https://github.com/fmtlib/fmt && cd fmt
        git checkout 10.1.0
        mkdir build && cd build
        cmake -DFMT_TEST=OFF ..
        make -j8
        sudo make install

    - name: Install mp-units
      shell: bash
      run: |
        git clone https://github.com/mpusz/mp-units && cd mp-units
        git checkout v2.1.0
        mkdir build && cd build
        cmake -DMP_UNITS_USE_FMTLIB=ON -DMP_UNITS_BUILD_LA=OFF ..
        make -j8
        sudo make install

